### ISSUE TITLE
isStateValid segfaults for "old" and default FCL

### ISSUE THREAD

**Issue by wxmerkt** [ipab-slmc/exotica#157]
This used to work.

```
#0  0x00007fffe78d6c48 in fcl::HierarchyTree<fcl::AABB>::topdown_0(__gnu_cxx::__normal_iterator<fcl::NodeBase<fcl::AABB>**, std::vector<fcl::NodeBase<fcl::AABB>*, std::allocator<fcl::NodeBase<fcl::AABB>*> > >, __gnu_cxx::__normal_iterator<fcl::NodeBase<fcl::AABB>**, std::vector<fcl::NodeBase<fcl::AABB>*, std::allocator<fcl::NodeBase<fcl::AABB>*> > >) () from /opt/ros/indigo/lib/libfcl.so
#1  0x00007fffe78d7331 in fcl::HierarchyTree<fcl::AABB>::init_0(std::vector<fcl::NodeBase<fcl::AABB>*, std::allocator<fcl::NodeBase<fcl::AABB>*> >&) () from /opt/ros/indigo/lib/libfcl.so
#2  0x00007fffe78d3df3 in fcl::DynamicAABBTreeCollisionManager::registerObjects(std::vector<fcl::CollisionObject*, std::allocator<fcl::CollisionObject*> > const&) () from /opt/ros/indigo/lib/libfcl.so
#3  0x00007fffde699dfd in exotica::CollisionSceneFCL::isStateValid (this=0x1d84680, self=<optimised out>, safe_distance=0)
    at 
~/dev_ws/exotica/exotations/collision_scene_fcl/src/CollisionSceneFCL.cpp:226
```

**Comment by VladimirIvan** [comment]
How can this be reproduced?
