### ISSUE TITLE
NumPy/SciPy/Matplotlib should be listed as dependancy/prerequisite

### ISSUE THREAD

**Issue by cmower** [ipab-slmc/exotica#490]
* I recently installed a clean version of Ubuntu 18, ROS Melodic, and EXOTica. 
* I forgot to install NumPy (and others `scipy matplotlib ipython jupyter pandas sympy nose`)
* When running `roslaunch exotica_examples python_ik.launch` the following error was thrown
```
Traceback (most recent call last):
  File "/home/chris/Documents/Projects/exotica_dev_ws/src/exotica/exotica_examples/scripts/example_ik", line 3, in <module>
    import pyexotica as exo
  File "/home/chris/Documents/Projects/exotica_dev_ws/devel/lib/python2.7/dist-packages/pyexotica/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 2, in <module>
  File "/home/chris/Documents/Projects/exotica_dev_ws/src/exotica/exotica_python/src/pyexotica/publish_trajectory.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 127, in <module>
    from matplotlib.rcsetup import defaultParams, validate_backend, cycler
  File "/usr/lib/python2.7/dist-packages/matplotlib/rcsetup.py", line 29, in <module>
    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern
  File "/usr/lib/python2.7/dist-packages/matplotlib/fontconfig_pattern.py", line 32, in <module>
    from backports.functools_lru_cache import lru_cache
ImportError: No module named functools_lru_cache
```
* Of course the solution was to install NumPy/SciPy/Matplotlib etc.
* NumPy/SciPy/Matplotlib should be listed in the prerequisites

**Comment by wxmerkt** [comment]
rosdep should have installed it. It did not cleanly exit for you as the ignored package wasn't available. It's not necessary to add it to the README explicitly.
